collection_name: agent
persist_directory: chroma_db
k: 3
data_path: data
md5_hex_store: md5.text
allowed_file_type: ["txt","pdf"]
chunk_size: 1000
chunk_overlap: 100
separators: ["\n\n","\n","。","！","？","."]

